const titleParser = require('./titleParser')
const Todo = require('../models/Todo')

module.exports = {
    renderHome: (req, res) => {
        res.render('blankIndex.ejs')
    },

    handleDrop: async (req, res) => {
        try {
          fileNames = req.body.names
          parsedTitles = await titleParser.parse(fileNames) 
          await Todo.create({todo: parsedTitles, completed: false})
      
          res.redirect('/renderWritten');
        } catch(err) {
          console.log(err)
        }
      },

      renderWritten: (req,res)=>{
        try{
            res.render('writtenIndex.ejs')
            console.log('active')
        }catch(err){
            console.log(err)
        }
      },
}


//From ChatGPT
//In an MVC (Model-View-Controller) architecture, it is not possible to access data generated by a POST request in a subsequent GET request without saving the data in a persistent storage such as a database. This is because the POST request and the GET request are independent of each other, and the data generated by the POST request is not automatically available to the GET request.

//what we need to do - store data in Mongo DB with the titleParser module
////access that data with a subsequent GET request and render it to the dom 
////access that data with a subsequent POST request and write the data to the xlsx document 

//Once all of that is done we can move on to building functionality that will actually read the doc 



//handleDrop: async (req, res) => {
    //    fileNames = req.body.names
    //    parsedTitles = await titleParser.parse(fileNames)
    //   const parsedTitlesJson = JSON.stringify(parsedTitles)
    //   console.log('one line above')
    //   DbController.write(parsedTitlesJson) 
  //    res.redirect('/renderWritten')
//  },